### ISSUE TITLE
Gate and Envelope Release Behavior

### ISSUE THREAD

**Issue by seriesof** [gesellkammer/sc-tx81z#1]
Closing the gate does not ramp down according to 'rel' time as described in code comments:

>   * If `gate` is closed while envelope has not reached 0, it ramps down
>       to 0 in `rel` time.

Setting gate to 0 cuts the audio and creates an audible click, despite long decay and release times. 

Tested using the code found in the help file (modified with slower envelope times). Same behavior with both MIDI and using the "a.set(\gate, 0);" approach. 

```
(
SynthDef(\tx81z_demo, {|gate=1, kfreq=220, vel=90, algorithm=0|
	var tx = Tx81z.ar(gate, velocity:vel, algorithm:algorithm,
		kfreq1:kfreq/2, kfreq2:kfreq/2*4.02, kfreq3:kfreq*0.996, kfreq4:kfreq,
		wave1:0, wave2:0, wave3:0, wave4:0,
		op1: 1, op2:0, op3:0, op4:0,
		att1: 16, att2: 23, att3: 23, att4: 23,
		dec1: 4, dec2: 7, dec3: 7, dec4: 7,
		sust1: 4, sust2: 5, sust3: 5, sust4: 5,
		ext1: 4, ext2: 5, ext3: 5, ext4: 5,
		rel1: 4, rel2: 4, rel3: 4, rel4: 4,
		feedback:0.91, doneAction:2);
	Out.ar(0, tx ! 2);
}).send;
)

(  // use a midi keyboard
~synths = Array.fill(128, nil);
MIDIFunc.noteOn({|vel, midinote|
	~synths[midinote] = Synth(\tx81z_demo, args:[kfreq:midinote.midicps, vel:vel, algorithm:4]);
});
MIDIFunc.noteOff({|vel, midinote|
	~synths[midinote].set(\gate, 0);
});
) 

a = Synth(\tx81z_demo, args:[freq:440, vel:90, algorithm:0]);
a.set(\gate, 0);
```

Bypassing MIDIFunc.noteOff by setting gate to 1 fixes the issue but quickly kills the cpu.

**Comment by gesellkammer** [comment]
fixed in 0c9eb326ce8183038db68ae74814af3fc97a0807
